name: Build and Deploy (branch: deploy)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build static export
        run: npm run build
        # Next com output:'export' cria a pasta out/

      - name: Add .nojekyll
        run: touch out/.nojekyll

      - name: Deploy to branch 'deploy'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: out
          clean: true
